clocks:
  - label: Seattle
    shortLabel: SEA
    timeZone: America/Los_Angeles
    format: h:mm a
  - label: Dublin
    shortLabel: DUB
    timeZone: Europe/Dublin
    format: h:mm a
updateInterval: 10
